### ISSUE TITLE
Prettier all rules

### ISSUE THREAD

**Issue by kcubero27** [kcubero27/react-template#6]
`{
  "printWidth": 80,
  "tabWidth": 2,
  "useTabs": false,
  "semi": false,
  "singleQuote": true,
  "trailingComma": "all",
  "bracketSpacing": false,
  "jsxBracketSameLine": false,
  "proseWrap": "always"
}`

Add a .prettierignore

**Comment by karencubero** [comment]
Refactor the current script:
`"prettier": "prettier --write --config ./.prettierrc '**/*.{ts,tsx,js,jsx,html,css,md,mdx}'",`
